_pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

_dream_bundle:
    resource: "@DreamBundle/Resources/config/routing.yml"
    prefix:   /

_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

_file_bundle:
    resource: "@GeekhubFileBundle/Resources/config/routing.yml"
    prefix:   /file

_imagine:
    resource: .
    type:     imagine

_fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
