profile_my_show:
    pattern:    /
    defaults:   { _controller: UserBundle:Profile:showMyProfile }

profile_stranger_show:
    pattern:    /{slug}/show
    defaults:   { _controller: UserBundle:Profile:showStrangerProfile }

ajax_update_about_me:
    pattern:    /ajax/update/about-me
    defaults:   { _controller: UserBundle:AjaxUser:updateUserAboutMe }

ajax_update_avatar:
    pattern:    /ajax/update/avatar
    defaults:   { _controller: UserBundle:AjaxUser:updateUserAvatar }

ajax_update_skype:
    pattern:    /ajax/update/skype
    defaults:   { _controller: UserBundle:AjaxUser:updateUserSkype }

ajax_update_phone:
    pattern:    /ajax/update/phone
    defaults:   { _controller: UserBundle:AjaxUser:updateUserPhone }

ajax_update_email:
    pattern:    /ajax/update/email
    defaults:   { _controller: UserBundle:AjaxUser:updateUserEmail }
