dream_homepage:
    pattern:  /
    defaults: { _controller: DreamBundle:Default:index }

dream_entity:
    resource: "@DreamBundle/Resources/config/routing/dream.yml"
    prefix:   /dream

dream_dreams:
    pattern:  /dreams
    defaults: { _controller: "DreamBundle:Dream:index" }

get_vimeo_thumbnail:
    pattern:  /get-vimeo-thumbnail/{videoId}
    defaults: { _controller: "DreamBundle:Default:getVimeoThumbnail" }

