dream_homepage:
    pattern:  /
    defaults: { _controller: DreamBundle:Default:index }

dream_dreams:
    pattern:  /dreams
    defaults: { _controller: "DreamBundle:Dream:index" }

dream_entity:
    resource: "@DreamBundle/Resources/config/routing/dream.yml"
    prefix:   /dream

dream_cbsupport:
    resource: "@DreamBundle/Resources/config/routing/cbsupport.yml"
    prefix:   /cbsupport

dream_emails:
    resource: "@DreamBundle/Resources/config/routing/notify.yml"
    prefix:   /notify
