notify_ajax_set_dream_success:
    pattern:  /set-success/{dreamId}
    defaults: { _controller: "DreamBundle:Notify:setAjaxDreamSuccess" }

notify_ajax_close_dream:
    pattern:  /close
    defaults: { _controller: "DreamBundle:Notify:setAjaxDreamClose" }
    requirements: { _method: post }
